### ISSUE TITLE
Add missing exports conditions

### ISSUE THREAD

**Issue by laxadev** [rozek/svelte-device-info#3]
You can find more information about this here https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by rozek** [comment]
Hi,

thank you very much for your notice - I've just added the required "export condition".

Could you please check if everything runs fine now?

Thanks in advance for your effort!

**Comment by laxadev** [comment]
Hi,

Yes, all good.
Thanks.
